### ISSUE TITLE
Create a Dashboard 

### ISSUE THREAD

**Issue by Govine-Jarrett** [devgovi/speed_tracker#2]
Create a dashboard so that the user can easily edit the following: 

- [x] Minimum upload speed 
- [x] Minimum download speed 
- [x] Email
- [x] Modem Location 
      This will be used in the email body,
      to help you keep track of which router.

**Comment by devbazregari** [comment]
hi bro I hope you're doing great. I'm not a pro but your app got my attention it seems interesting and I want to give it a shot if you allow me.

**Comment by Govine-Jarrett** [comment]
> hi bro I hope you're doing great. I'm not a pro but your app got my attention it seems interesting and I want to give it a shot if you allow me.

Hey, you're more than welcome to give it a shot.

Note:
I will be refactoring the file structure in the next update.

**Comment by Govine-Jarrett** [comment]
![Speed_Tracker_Screenshot](https://user-images.githubusercontent.com/105304154/193377294-6fa7549f-ab92-4cf7-8376-f78a9854c48c.png)
